### ISSUE TITLE
无线网卡的安装问题

### ISSUE THREAD

**Issue by wander555** [paranoid2006/MAXSUN-H610ITX-Hackintosh#1]
你好，我的配置和你一模一样就是无线网卡还没有买，也想买BCM943602cs，我看了下主板带的天线只有两个，而且屏蔽罩很小，请问你是怎么安装上网卡的？谢谢

**Comment by paranoid2006** [comment]
我移除了那种外置的棍棒天线，上淘宝买3根 4代IPEX转SMA母头(内针)天线，10cm长的就可以，直接贴在无线网卡旁边就可以了。

**Comment by wander555** [comment]
> 我移除了那种外置的棍棒天线，棍棒天线会导致小铁盒子无法安装BCM943602CS+转接卡，上淘宝买3根4代IPEX天线，直接贴在无线网卡旁边就可以了，1.3元一根。 【淘宝】https://m.tb.cn/h.50bHETl?tk=s3bTdtfkdpI CZ3457

非常感谢！
